import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage();
const failed: Array<{ url: string; status: number }> = [];
page.on("response", (r) => { if (r.status() >= 400) failed.push({ url: r.url(), status: r.status() }); });
await page.goto("https://docs.potenfyr.in/repo/authcore", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(2400);
console.log("failing resources:");
[...new Map(failed.map(f => [f.url, f.status])).entries()].forEach(([u, s]) => console.log(`  ${s}  ${u}`));
await browser.close();
